name: Publish XLUM to test.pypi.org


if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
uses: pypa/gh-action-pypi-publish@release/v1
with:
  password: ${{ secrets.TESTPYPI_API_TOKEN }}